// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.12.4
// source: data_node.proto

package data_node_keeper

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReceiveUploadedFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileContent string `protobuf:"bytes,1,opt,name=fileContent,proto3" json:"fileContent,omitempty"`
	FileName    string `protobuf:"bytes,2,opt,name=fileName,proto3" json:"fileName,omitempty"`
}

func (x *ReceiveUploadedFileRequest) Reset() {
	*x = ReceiveUploadedFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_node_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceiveUploadedFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveUploadedFileRequest) ProtoMessage() {}

func (x *ReceiveUploadedFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_node_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveUploadedFileRequest.ProtoReflect.Descriptor instead.
func (*ReceiveUploadedFileRequest) Descriptor() ([]byte, []int) {
	return file_data_node_proto_rawDescGZIP(), []int{0}
}

func (x *ReceiveUploadedFileRequest) GetFileContent() string {
	if x != nil {
		return x.FileContent
	}
	return ""
}

func (x *ReceiveUploadedFileRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type ReceiveUploadedFileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *ReceiveUploadedFileResponse) Reset() {
	*x = ReceiveUploadedFileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_node_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceiveUploadedFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveUploadedFileResponse) ProtoMessage() {}

func (x *ReceiveUploadedFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_node_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveUploadedFileResponse.ProtoReflect.Descriptor instead.
func (*ReceiveUploadedFileResponse) Descriptor() ([]byte, []int) {
	return file_data_node_proto_rawDescGZIP(), []int{1}
}

func (x *ReceiveUploadedFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_data_node_proto protoreflect.FileDescriptor

var file_data_node_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x22, 0x5a, 0x0a, 0x1a,
	0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x46,
	0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x66, 0x69,
	0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x66, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x37, 0x0a, 0x1b, 0x52, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x32, 0x70, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x64, 0x0a,
	0x13, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64,
	0x46, 0x69, 0x6c, 0x65, 0x12, 0x25, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x6e, 0x6f, 0x64, 0x65,
	0x2e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64,
	0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x64, 0x61,
	0x74, 0x61, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x13, 0x5a, 0x11, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x6e, 0x6f, 0x64, 0x65,
	0x5f, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_data_node_proto_rawDescOnce sync.Once
	file_data_node_proto_rawDescData = file_data_node_proto_rawDesc
)

func file_data_node_proto_rawDescGZIP() []byte {
	file_data_node_proto_rawDescOnce.Do(func() {
		file_data_node_proto_rawDescData = protoimpl.X.CompressGZIP(file_data_node_proto_rawDescData)
	})
	return file_data_node_proto_rawDescData
}

var file_data_node_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_data_node_proto_goTypes = []interface{}{
	(*ReceiveUploadedFileRequest)(nil),  // 0: data_node.ReceiveUploadedFileRequest
	(*ReceiveUploadedFileResponse)(nil), // 1: data_node.ReceiveUploadedFileResponse
}
var file_data_node_proto_depIdxs = []int32{
	0, // 0: data_node.DataNode.ReceiveUploadedFile:input_type -> data_node.ReceiveUploadedFileRequest
	1, // 1: data_node.DataNode.ReceiveUploadedFile:output_type -> data_node.ReceiveUploadedFileResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_data_node_proto_init() }
func file_data_node_proto_init() {
	if File_data_node_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_data_node_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceiveUploadedFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_node_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceiveUploadedFileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_data_node_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_data_node_proto_goTypes,
		DependencyIndexes: file_data_node_proto_depIdxs,
		MessageInfos:      file_data_node_proto_msgTypes,
	}.Build()
	File_data_node_proto = out.File
	file_data_node_proto_rawDesc = nil
	file_data_node_proto_goTypes = nil
	file_data_node_proto_depIdxs = nil
}
